# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ENV.delete('GEM_PATH')
    ENV.delete('GEM_HOME')
    # build_app(
    #   workspace: "Runner.xcworkspace",
    #   scheme: "Runner",
    #   export_method: "app-store",
    # )
    upload_to_testflight(
      distribute_external: false,
      notify_external_testers: false,
      submission_information: {
        export_compliance_uses_encryption: false,
      }
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    ENV.delete('GEM_PATH')
    ENV.delete('GEM_HOME')
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true,
      force: true,
      submission_information: {
        export_compliance_uses_encryption: false,
      }
    )
  end
end