# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  root = File.expand_path("../..", __dir__)

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ENV.delete('GEM_PATH')
    ENV.delete('GEM_HOME')
    Dir.chdir(root) { sh("flutter", "build", "ipa", "--release") }
    upload_to_testflight(
      ipa: Dir["#{root}/build/ios/ipa/*.ipa"].first,
      distribute_external: true,
      notify_external_testers: true,
      groups: ["Tester Esterni"],
      uses_non_exempt_encryption: false,
      changelog: "Migliorata stabilità dell'app e sistemati fastidiosi bugs!",
    )
  end

  desc "Update App Store metadata and localizations only (no binary upload)"
  lane :update_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true,
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    ENV.delete('GEM_PATH')
    ENV.delete('GEM_HOME')
    Dir.chdir(root) { sh("flutter", "build", "ipa", "--release") }
    upload_to_app_store(
      ipa: Dir["#{root}/build/ios/ipa/*.ipa"].first,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      submission_information: {
        export_compliance_uses_encryption: false,
      }
    )
  end
end
